

export const borough = [
  { value: 'Barking & Dagenham', label: 'Barking & Dagenham' },
  { value: 'Barnet', label: 'Barnet' },
  { value: 'Bexley', label: 'Bexley' },
  { value: 'Brent', label: 'Brent' },
  { value: 'Bromley', label: 'Bromley' },
  { value: 'Camden', label: 'Camden' },
  { value: 'City of London', label: 'City of London' },
  { value: 'Croydon', label: 'Croydon' },
  { value: 'Ealing', label: 'Ealing' },
  { value: 'Enfield', label: 'Enfieldm' },
  { value: 'Greenwich', label: 'Greenwich' },
  { value: 'Hackney', label: 'Hackney' },
  { value: 'Hammersmith & Fulham', label: 'Hammersmith & Fulham' },
  { value: 'Haringey', label: 'Haringey' },
  { value: 'Harrow', label: 'Harrow' },
  { value: 'Havering', label: 'Havering' },
  { value: 'Hillingdon', label: 'Hillingdon' },
  { value: 'Hounslow', label: 'Hounslow' },
  { value: 'Islington', label: 'Islington' },
  { value: 'Kingston upon Thames', label: 'Kingston upon Thames' },
  { value: 'Lambeth', label: 'Lambeth' },
  { value: 'Lewisham', label: 'Lewisham' },
  { value: 'Merton', label: 'Merton' },
  { value: 'Newham', label: 'Newham' },
  { value: 'Redbridge', label: 'Redbridge' },
  { value: 'Richmond upon Thames', label: 'Richmond upon Thames' },
  { value: 'Southwark', label: 'Southwark' },
  { value: 'Sutton', label: 'Sutton' },
  { value: 'Tower Hamlets', label: 'Tower Hamlets' },
  { value: 'Waltham Forest', label: 'Waltham Forest' },
  { value: 'Wandsworth', label: 'Wandsworth' },
  { value: 'Westminster', label: 'Westminster' }
]
