
export const interest = [
  { value: 'baking', label: 'baking' },
  { value: 'dance', label: 'dance' },
  { value: 'sport', label: 'sport' },
  { value: 'reading', label: 'reading' },
  { value: 'fashion', label: 'fashion' },
  { value: 'coding', label: 'coding' },
  { value: 'travel', label: 'travel' },
  { value: 'walking', label: 'walking' },
  { value: 'performance', label: 'performance' },
  { value: 'art', label: 'art' },
  { value: 'outdoors', label: 'outdoors' },
  { value: 'activities', label: 'activities' },
  { value: 'climbing', label: 'climbing' },
  { value: 'wildlife', label: 'wildlife' },
  { value: 'animals', label: 'animals' },
  { value: 'pets', label: 'pets' },
  { value: 'dogs', label: 'dogs' },
  { value: 'cats', label: 'cats' },
  { value: 'adventure', label: 'adventure' },
  { value: 'drinking', label: 'drinking' },
  { value: 'gardening', label: 'gardening' },
  { value: 'community', label: 'community' },
  { value: 'charity', label: 'charity' },
  { value: 'family', label: 'family' },
  { value: 'children', label: 'children' },
  { value: 'design', label: 'design' },
  { value: 'campainging', label: 'campainging' },
  { value: 'theatre', label: 'theatre' },
  { value: 'sight seeing', label: 'sight seeing' },
  { value: 'education', label: 'education' },
  { value: 'mindfulness', label: 'mindfulness' },
  { value: 'drinking', label: 'drinking' },
  { value: 'crafts', label: 'crafts' },
  { value: 'prayer', label: 'prayer' },
  { value: 'christianity', label: 'christianity' },
  { value: 'laughter', label: 'laughter' },
  { value: 'stand-up', label: 'stand-up' },
  { value: 'companionship', label: 'companionship' },
  { value: 'workshop', label: 'workshop' },
  { value: 'crafts', label: 'crafts' },
  { value: 'open-mic', label: 'open-mic' },
  { value: 'kids', label: 'kids' },
  { value: 'climbing', label: 'climbing' },
  { value: 'history', label: 'history' },
  { value: 'tourist', label: 'tourist' },
  { value: 'theatre', label: 'theatre' },
  { value: 'museum', label: 'museum' },
  { value: 'nature', label: 'nature' },
  { value: 'painting', label: 'painting' },
  { value: 'fun', label: 'fun' },
  { value: 'gardening', label: 'gardening' },
  { value: 'play', label: 'play' },
  { value: 'picnic', label: 'picnic' },
  { value: 'charity', label: 'charity' },
  { value: 'friendship', label: 'friendship' },
  { value: 'homelessness', label: 'homelessness' },
  { value: 'listening', label: 'listening' },
  { value: 'football', label: 'football' },
  { value: 'talking', label: 'talking' },
  { value: 'tournament', label: 'tournament' },
  { value: 'ball-game', label: 'ball-game' },
  { value: 'dogs', label: 'dogs' },
  { value: 'cats', label: 'cats' },
  { value: 'sober', label: 'sober' },
  { value: 'day-time', label: 'day-time' },
  { value: 'walking', label: 'walking' },
  { value: 'breakfast', label: 'breakfast' },
  { value: 'morning', label: 'morning' },
  { value: 'girls-only', label: 'girls-only' },
  { value: 'chit-chat', label: 'chit-chat' },
  { value: 'strategy-game', label: 'strategy-game' },
  { value: 'mindfullness', label: 'mindfullness' },
  { value: 'vintage', label: 'vintage' },
  { value: 'hipster', label: 'hipster' },
  { value: 'fantasy', label: 'fantasy' },
  { value: 'nerdy', label: 'nerdy' },
  { value: 'role-play', label: 'role-play' },
  { value: 'comics', label: 'comics' },
  { value: 'langauges', label: 'langauges' },
  { value: 'french', label: 'french' },
  { value: 'meat', label: 'meat' },
  { value: 'jamming', label: 'jamming' },
  { value: 'intellectual', label: 'intellectual' },
  { value: 'biscuits', label: 'biscuits' },
  { value: 'baby-animals', label: 'baby-animals' },
  { value: 'lgbtq', label: 'lgbtq' },
  { value: 'lads', label: 'lads' },
  { value: 'banter', label: 'banter' },
  { value: 'wine', label: 'wine' },
  { value: 'beer', label: 'beer' },
  { value: 'fine-dining', label: 'fine-dining' },
  { value: 'spanish', label: 'spanish' },
  { value: 'restaurant', label: 'restaurant' },
  { value: 'politics', label: 'politics' },
  { value: 'green', label: 'green' },
  { value: 'environmental', label: 'environmental' },
  { value: 'mental-health', label: 'mental-health' },
  { value: 'buddhism', label: 'buddhism' }






]
