
export const interest = [
  { value: 'Baking', label: 'Baking' },
  { value: 'Dance', label: 'Dance' },
  { value: 'Sport', label: 'Sport' },
  { value: 'Reading', label: 'Reading' },
  { value: 'Fashion', label: 'Fashion' },
  { value: 'Coding', label: 'Coding' },
  { value: 'Travel', label: 'Travel' },
  { value: 'Walking', label: 'Walking' },
  { value: 'Performance', label: 'Performance' },
  { value: 'Art', label: 'Art' },
  { value: 'Outdoors', label: 'Outdoors' },
  { value: 'Activities', label: 'Activities' },
  { value: 'Climbing', label: 'Climbing' },
  { value: 'Wildlife', label: 'Wildlife' },
  { value: 'Animals', label: 'Animals' },
  { value: 'Pets', label: 'Pets' },
  { value: 'Dogs', label: 'Dogs' },
  { value: 'Cats', label: 'Cats' },
  { value: 'Adventure', label: 'Adventure' },
  { value: 'Drinking', label: 'Drinking' },
  { value: 'Gardening', label: 'Gardening' },
  { value: 'Community', label: 'Community' },
  { value: 'Charity', label: 'Charity' },
  { value: 'Family', label: 'Family' },
  { value: 'Children', label: 'Children' },
  { value: 'Design', label: 'Design' },
  { value: 'Campainging', label: 'Campainging' },
  { value: 'Theatre', label: 'Theatre' },
  { value: 'Sight Seeing', label: 'Sight Seeing' },
  { value: 'Education', label: 'Education' },
  { value: 'Mindfulness', label: 'Mindfulness' },
  { value: 'Drinking', label: 'Drinking' },
  { value: 'Sight Seeing', label: 'Sight Seeing' },
  { value: 'Partying', label: 'Partying' },
  { value: 'Clubbing', label: 'Clubbing' },
  { value: 'Pubs', label: 'Pubs' }
]
